LYTESCOPE_BASE_URL="https://www.lytescope.com"
LYTESCOPE_AGENT_UUID=""
LYTESCOPE_AGENT_SIGNING_SECRET=""
LYTESCOPE_ENDPOINT=""
LYTESCOPE_STATUS_ENDPOINT=""
LYTESCOPE_AGENT_SIGNATURE_VERSION="v1"
LYTESCOPE_AGENT_VERSION="0.1.13"